location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/vins_mono
    name: vins_mono
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/vins_mono
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_vins_mono_estimator_plugin
    name: mrs_vins_mono_estimator_plugin
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_vins_mono_estimator_plugin
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_vins_republisher
    name: mrs_vins_republisher
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_vins_republisher
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_vins_imu_filter
    name: mrs_vins_imu_filter
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_vins_imu_filter
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
