mrs_uav_managers:

  estimation_manager:

    state_estimators: [
     "gps_baro",
     "vins_mono"
    ]

    initial_state_estimator: "gps_baro" # will be used as the first state estimator
    agl_height_estimator: "" # only slightly filtered height for checking min height (not used in control feedback)

    # namespace of the state estimator
    vins_mono:

      address: "vins_mono/VinsMonoEstimatorPlugin"

      requires: # data required from the hw api
        gnss: false
        imu: false
        distance_sensor: false
        altitude: false
        magnetometer_heading: false
        position: false
        orientation: true
        velocity: true
        angular_velocity: true

      override_frame_id: # override the default frame_id with a custom one 
        enabled: false
        frame_id: "vio_origin" # the desired frame_id without the UAV namespace

      estimators: # the names of the partial estimators
        lateral:
          name: "lat_vins_mono"
        altitude:
          name: "alt_vins_mono"
          # name: "alt_garmin"
        heading:
          name: "hdg_vins_mono"
          passthrough: false # if true, then heading is not estimated but passed through from the orientation topic

      topics:
        orientation: "hw_api/orientation" # orientation passthrough
        angular_velocity: "hw_api/angular_velocity" # angular velocity passthrough

      # namespace of the altitude estimator
      alt_vins_mono: # namespace of the altitude estimator

        max_flight_z: 100.0 # [m] maximum allowed flight Z (in the estimator frame)

        innovation:
          limit: 1.0 # [m] innovation limit that will trigger action
          action: "switch" # {"eland", "switch", "mitigate"}

        repredictor: # repredictor for correct fusion of delayed measurements
          enabled: true
          buffer_size: 200 # [samples] how many states and corrections are kept in history (i.e. estimator running at the default 100 Hz rate will be able to fuse corrections with up to 2 s delay with buffer size of 200 samples)

        process_noise: # process noise covariance (Q)
          pos: 0.1 # position state
          vel: 1.0 # velocity state
          acc: 1.0 # acceleration state

        corrections: [
          "pos_vins_mono",
          "vel_vins_mono"
        ]

        pos_vins_mono:
          state_id: 0 # 0 - position, 1 - velocity, 2 - acceleration
          noise: 0.01 # measurement noise covariance (R)
          noise_unhealthy_coeff: 100.0 # covariance gets multiplied by this coefficient when correction is unhealthy (R)
          message:
            type: "nav_msgs/Odometry"
            topic: "vins_republisher/odom" # without uav namespace
            limit: 
              delay: 1.0 # [s] messages with higher delay will flag correction as unhealthy
              time_since_last: 0.5 # [s] larger time step between messages will flag correction as unhealthy

          processors: [] # types of processors attached to this measurement

        vel_vins_mono:
          state_id: 1 # 0 - position, 1 - velocity, 2 - acceleration
          noise: 0.01 # measurement noise covariance (R)
          noise_unhealthy_coeff: 100.0 # covariance gets multiplied by this coefficient when correction is unhealthy (R)
          body_frame: true
          message:
            type: "nav_msgs/Odometry"
            topic: "vins_republisher/odom" # without uav namespace
            limit: 
              delay: 1.0 # [s] messages with higher delay will flag correction as unhealthy
              time_since_last: 0.5 # [s] larger time step between messages will flag correction as unhealthy

          processors: [] # types of processors attached to this measurement

      # namespace of the heading estimator
      hdg_vins_mono: # namespace of the heading estimator

        max_flight_z: 100.0 # [m] maximum allowed flight Z (in the estimator frame)

        position_innovation_limit: 1.0 # [rad] innovation limit that will trigger switch to other estimator

        repredictor: # repredictor for correct fusion of delayed measurements
          enabled: true
          buffer_size: 200 # [samples] how many states and corrections are kept in history (i.e. estimator running at the default 100 Hz rate will be able to fuse corrections with up to 2 s delay with buffer size of 200 samples)

        process_noise: # process noise covariance (Q)
          pos: 0.1 # position state
          vel: 0.1 # velocity state

        corrections: [
          "hdg_vins_mono"
        ]

        hdg_vins_mono:
          state_id: 0 # 0 - position, 1 - velocity, 2 - acceleration
          noise: 0.0001 # measurement noise covariance (R)
          noise_unhealthy_coeff: 100.0 # covariance gets multiplied by this coefficient when correction is unhealthy (R)
          message:
            type: "nav_msgs/Odometry"
            topic: "vins_republisher/odom" # without uav namespace
            limit: 
              delay: 1.0 # [s] messages with higher delay will flag correction as unhealthy
              time_since_last: 0.5 # [s] larger time step between messages will flag correction as unhealthy

          processors: [] # types of processors attached to this measurement

      # namespace of the lateral estimator
      lat_vins_mono: # namespace of the lateral estimator

        hdg_source_topic: "vins_mono/hdg_vins_mono/output" # [mrs_uav_state_estimation/EstimatorOutput]

        max_flight_z: 100.0 # [m] maximum allowed flight Z (in the estimator frame)

        innovation:
          limit: 1.0 # [m] innovation limit that will trigger action
          action: "eland" # {"eland", "switch", "mitigate"}

        repredictor: # repredictor for correct fusion of delayed measurements
          enabled: true
          buffer_size: 200 # [samples] how many states and corrections are kept in history (i.e. estimator running at the default 100 Hz rate will be able to fuse corrections with up to 2 s delay with buffer size of 200 samples)

        process_noise: # process noise covariance (Q)
          pos: 0.1 # position state
          vel: 1.0 # velocity state
          acc: 1.0 # acceleration state

        corrections: [
          "pos_vins_mono",
          "vel_vins_mono"
        ]

        pos_vins_mono:
          state_id: 0 # 0 - position, 1 - velocity, 2 - acceleration
          noise: 0.01 # measurement noise covariance (R)
          noise_unhealthy_coeff: 100.0 # covariance gets multiplied by this coefficient when correction is unhealthy (R)
          message:
            type: "nav_msgs/Odometry"
            topic: "vins_republisher/odom" # without uav namespace
            limit: 
              delay: 1.0 # [s] messages with higher delay will flag correction as unhealthy
              time_since_last: 0.5 # [s] larger time step between messages will flag correction as unhealthy

          processors: [] # types of processors attached to this measurement

        vel_vins_mono:
          state_id: 1 # 0 - position, 1 - velocity, 2 - acceleration
          noise: 0.01 # measurement noise covariance (R)
          noise_unhealthy_coeff: 100.0 # covariance gets multiplied by this coefficient when correction is unhealthy (R)
          body_frame: true # velocity is in body frame from open_vins
          message:
            type: "nav_msgs/Odometry"
            topic: "vins_republisher/odom" # without uav namespace
            limit: 
              delay: 1.0 # [s] messages with higher delay will flag correction as unhealthy
              time_since_last: 0.5 # [s] larger time step between messages will flag correction as unhealthy

          processors: [] # types of processors attached to this measurement

  constraint_manager:

    estimator_types: [
      "gps_baro",
      "vins_mono"
    ]

    constraints: [
      "slow",
      "medium",
      "fast"
    ]

    # list of allowed gains per odometry mode
    allowed_constraints:
      gps_baro: ["slow", "medium", "fast"]
      vins_mono: ["slow", "medium", "fast"]

    # those gains will be used automatically when a localization mode switches
    # and the current gains are not in the allowed list (next paragraphs)
    default_constraints:
      gps_baro: "slow"
      vins_mono: "slow"

  gain_manager:

    estimator_types: [
      "gps_baro",
      "vins_mono"
    ]

    gains: [
      "supersoft"
    ]

    # list of allowed gains per odometry mode
    allowed_gains:
      gps_baro: ["supersoft"]
      vins_mono: ["supersoft"]

    # those gains will be used automatically when a localization mode switches
    # and the current gains are not in the allowed list (next paragraphs)
    default_gains:
      gps_baro: "supersoft"
      vins_mono: "supersoft"

  transform_manager:

    vins_mono:
      odom_topic: "odom" # name of the topic (expects nav_msgs/Odometry topic type)
      tf_from_attitude: # used for transforming velocities before full transform is available
        enabled: true
        attitude_topic: "attitude" # name of the attitude topic(expects geometry_msgs/QuaternionStamped topic type)
      namespace: "estimation_manager/vins_mono" # the namespace of the topic (usually the node that publishes the topic)
      utm_based: false # if true, will publish tf to utm_origin
      inverted: true # publish as inverted tf (the default for inverted mrs tf tree convention)
      republish_in_frames: [] # the odometry message will be transformed and republished in the specified frames
